import Head from 'next/head'

const twitterHandle = '@bacondotbuild'

const Meta = ({ title, siteName }: { title: string; siteName?: string }) => (
  <Head>
    <link rel='manifest' href='/manifest.json' />
    <meta name='mobile-web-app-capable' content='yes' />
    <meta name='apple-mobile-web-app-capable' content='yes' />
    <meta name='msapplication-starturl' content='/' />
    <meta
      name='viewport'
      content='width=device-width, initial-scale=1, shrink-to-fit=no'
    />
    <meta charSet='utf-8' />
    <meta name='description' content='Generated by create-t3-app' />

    {/* Twitter */}
    <meta name='twitter:card' content='summary' key='twcard' />
    <meta name='twitter:creator' content={twitterHandle} key='twhandle' />

    {/* Open Graph */}
    {/* <meta property='og:url' content={currentURL} key='ogurl' /> */}
    <meta property='og:image' content='/icon.png' key='ogimage' />
    <meta
      property='og:site_name'
      content={siteName ?? title}
      key='ogsitename'
    />
    <meta property='og:title' content={title} key='ogtitle' />
    <meta
      property='og:description'
      content='Generated by create-t3-app'
      key='ogdesc'
    />

    <meta name='theme-color' content='#15232d' />
    <link rel='icon' href='/favicon.png' />
    <link rel='shortcut icon' href='/favicon.png' />
    <link rel='apple-touch-icon' sizes='57x57' href='/icon.png' />
    <link rel='apple-touch-icon' sizes='72x72' href='/icon.png' />
    <link rel='apple-touch-icon' sizes='114x114' href='/icon.png' />
    <link rel='apple-touch-icon' sizes='144x144' href='/icon.png' />
    <link
      href='splash.png'
      media='(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)'
      rel='apple-touch-startup-image'
    />
    <title>{title}</title>
  </Head>
)

export default Meta
